---
project_name: grafaman

archives:
- id: grafaman
  files:
  - LICENSE
  format: tar.gz
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    386:    32bit
    amd64:  64bit
    darwin: macOS
    linux:  Linux

brews:
- name: grafaman
  commit_author:
    name:  Kamil Samigullin
    email: kamil@samigullin.info
  description: Metrics coverage reporter for Graphite and Grafana.
  folder: Formula
  homepage: https://github.com/kamilsk/grafaman
  github:
    owner: kamilsk
    name:  homebrew-tap
  install: |
    bin.install "grafaman"
    output = Utils.popen_read("#{bin}/grafaman completion bash")
    (bash_completion/"grafaman").write output
    output = Utils.popen_read("#{bin}/grafaman completion zsh")
    (zsh_completion/"_grafaman").write output
    prefix.install_metafiles
  test: |
    system "#{bin}/grafaman --version"

builds:
- binary: grafaman
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: kamilsk
    name:  grafaman
