# This file was generated by GoReleaser. DO NOT EDIT.
class Grafaman < Formula
  desc "Metrics coverage reporter for Graphite and Grafana."
  homepage "https://github.com/kamilsk/grafaman"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kamilsk/grafaman/releases/download/v0.0.1/grafaman_0.0.1_macOS-64bit.tar.gz"
    sha256 "348cb9b1d244a911a0a21512fb336e156b44b225fd53ba011aa399750c5409ed"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/grafaman/releases/download/v0.0.1/grafaman_0.0.1_Linux-64bit.tar.gz"
      sha256 "a7779d850fab460b67af28b614d2ae0bd4630b97730cfc94f714044be180a6a8"
    end
  end

  def install
    bin.install "grafaman"
    output = Utils.popen_read("#{bin}/grafaman completion bash")
    (bash_completion/"grafaman").write output
    output = Utils.popen_read("#{bin}/grafaman completion zsh")
    (zsh_completion/"_grafaman").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/grafaman --version"
  end
end
